import { Archive, CalendarDays, CheckSquare, Search, Trash2, UserRound } from 'lucide-react'
import DotSelect from '../ui/DotSelect'
import { TASK_CATEGORY_OPTIONS, TASK_PRIORITY_OPTIONS, TASK_STATUS_OPTIONS } from '../../utils/taskOptions'

export default function AssociatesTasksCard({ tasks, selectedIds, selectedCount, allSelected, search, statusFilter, priorityFilter, onSearch, onStatusFilter, onPriorityFilter, onToggle, onToggleAll, onUpdate, onArchive, onDeleteSelected }) {
  return (
    <section className="rounded-2xl border border-gray-100 bg-white px-5 py-8 shadow-card sm:px-6 sm:py-8">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
        <h2 className="flex items-center gap-2 text-lg font-semibold text-primary"><CheckSquare className="h-5 w-5" /> All Tasks</h2>
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
          <label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" /><input aria-label="Search tasks" value={search} onChange={(e) => onSearch(e.target.value)} placeholder="Search tasks, assignees, categories..." className="h-10 w-full rounded-lg border-0 pl-9 pr-3 text-sm outline-none ring-1 ring-transparent focus:ring-gold-light sm:w-80" /></label>
          <select aria-label="Filter by status" value={statusFilter} onChange={(e) => onStatusFilter(e.target.value)} className="h-10 rounded-lg border-0 px-3 text-sm outline-none"><option>All Status</option><option>PENDING</option><option>IN PROGRESS</option><option>COMPLETED</option><option>OVERDUE</option></select>
          <select aria-label="Filter by priority" value={priorityFilter} onChange={(e) => onPriorityFilter(e.target.value)} className="h-10 rounded-lg border-0 px-3 text-sm outline-none"><option>All Priority</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select>
        </div>
      </div>
      {/* Bulk bar: appears as soon as Select All (or any row checkbox) ticks a task. */}
      {selectedCount > 0 && <div role="region" aria-label="Task bulk actions" className="mt-7 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 animate-fade-in"><p className="text-[13px] font-medium text-blue-600">{selectedCount} task(s) selected</p><button type="button" onClick={onDeleteSelected} className="inline-flex h-12 items-center gap-2 rounded-xl border border-gray-200 bg-white px-6 text-sm font-bold text-red-600 shadow-sm transition-colors hover:bg-red-50"><Trash2 className="h-4 w-4" aria-hidden="true" /> Delete Selected</button></div>}
      <div className="mt-7 flex flex-wrap items-center justify-between gap-4"><label className="inline-flex items-center gap-2 text-xs text-text-secondary"><input type="checkbox" aria-label="Select all tasks" checked={allSelected} onChange={onToggleAll} className="h-4 w-4 accent-primary" /> Select All</label><button type="button" onClick={onArchive} className="inline-flex h-11 items-center gap-2 rounded-xl border-2 border-gold-light/50 px-6 text-xs font-semibold text-primary hover:bg-cream-light"><Archive className="h-4 w-4" /> Archive Completed</button></div>
      <div className="mt-4 overflow-x-auto">
        <table className="w-full min-w-[930px] border-collapse text-left"><thead className="bg-slate-50 text-sm font-semibold text-primary"><tr><th className="w-10 px-4 py-4"></th><th className="px-2 py-4">Task ↕</th><th className="px-2 py-4">Assigned To ↕</th><th className="px-2 py-4">Due Date ↕</th><th className="px-2 py-4">Priority ↕</th><th className="px-2 py-4">Category ↕</th><th className="px-2 py-4">Status</th></tr></thead><tbody>
          {tasks.map((task, index) => <tr key={task.id} className="border-b border-gray-100 text-sm"><td className="px-4 py-4"><input type="checkbox" aria-label={`Select task ${task.title}`} checked={selectedIds.has(task.id)} onChange={() => onToggle(task.id)} className="h-4 w-4 accent-primary" /></td><td className="px-2 py-4"><div className="flex gap-2"><span className="inline-flex h-7 min-w-8 items-center justify-center rounded bg-cream px-2 font-semibold text-primary">{index + 1}.</span><div><p className="font-semibold text-primary">{task.title}</p><p className="text-xs text-text-secondary">{task.details}</p></div></div></td><td className="px-2 py-4"><p className="flex items-center gap-2"><UserRound className="h-4 w-4 text-gray-400" />{task.assignee}</p><p className="pl-6 text-[11px] text-text-muted">by {task.created_by}</p></td><td className="px-2 py-4"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-gray-400" />{task.due_date}</span></td><td className="px-2 py-4"><DotSelect label={`Priority for ${task.title}`} value={task.priority} options={TASK_PRIORITY_OPTIONS} onChange={(value) => onUpdate(task.id, 'priority', value)} menuClassName="w-32" /></td><td className="px-2 py-4"><DotSelect label={`Category for ${task.title}`} value={task.category} options={TASK_CATEGORY_OPTIONS} onChange={(value) => onUpdate(task.id, 'category', value)} /></td><td className="px-2 py-4"><DotSelect label={`Status for ${task.title}`} value={task.status} options={TASK_STATUS_OPTIONS} onChange={(value) => onUpdate(task.id, 'status', value)} menuClassName="w-36" /></td></tr>)}
        </tbody></table>
      </div>
    </section>
  )
}
